on: [push]

jobs:
  Demo_job:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set status
        id: set_status
        run: |
          git config --global --add safe.directory '*'
          STATUS="$(git status)" 
          STATUS="${STATUS//'%'/'%25'}"
          STATUS="${STATUS//$'\n'/'%0A'}"
          STATUS="${STATUS//$'\r'/'%0D'}"
          echo "::set-output name=STATUS::$STATUS"
             
      - name: set hash ID
        id: Set_hash_ID
        run: |
          echo "::set-output name=HASH_ID::$( git log --format="%H" -n 1)"
      
      - name: execution-checker 1
        uses: ./
        id: execution_checker_1
        with:
          Flag: '-e'
          Hash: "${{ steps.Set_hash_ID.outputs.HASH_ID }}"
          Log_status: '${{ steps.set_status.outputs.STATUS }}'
      
      - name: Local_hash_ID
        id: Local_hash_ID
        run: |
          note="${{ steps.execution_checker_1.outputs.Encrypted }}"
          echo $note
          note="${note//'%'/'%25'}"
          note="${note//$'\n'/'%0A'}"
          note="${note//$'\r'/'%0D'}"
          git notes add -f -m "$note"

  Check_locally_execution:
    runs-on: ubuntu-latest
    name: Check_locally_execution
    needs: Demo_job
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
             
      - name: Get_hash_ID
        id: Get_hash_ID
        run: |
          git config --global --add safe.directory '*'
          echo "::set-output name=HASH_ID::$( git log --format="%H" -n 1)"
      
      - name: set notes
        id: Set_notes
        run: |
          notes="$( git notes show ${{ steps.Get_hash_ID.outputs.HASH_ID }})"
          echo "::set-output name=NOTES::$notes"
  
      - name: execution-checker-1
        uses: ./
        id: execution-checker-1
        with:
          Flag: '-c'
          Hash: ${{ steps.Get_hash_ID.outputs.HASH_ID }}
          Encrypted_Hash: '${{ steps.Set_notes.outputs.NOTES }}'