on: [push]

jobs:
  Demo_job:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Demo
        id: Demo
        uses: ./
        with:
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Log_status: 'Done'
      - name: Get the output Encrypted
        run: echo "${{ steps.Demo.outputs.Encrypted }}"

      - name: Demo_1
        id: Demo_1
        uses: ./
        with:
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Log_status: 'nothing to commit, working tree clean'
      - name: Get the output Encrypted 1
        run: echo "${{ steps.Demo_1.outputs.Encrypted }}"  