on: [push]

jobs:
  Demo_job:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Demo
        id: Demo
        uses: ./
        with:
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Log_status: "On branch main
            Your branch is ahead of 'origin/main' by 1 commit.
              (use git push to publish your local commits)

              Changes not staged for commit
              (use git add/rm <file>... to update what will be committed)
            (use git restore <file>... to discard changes in working directory)
            modified   bin/encrypt.sh
            modified   output.bin
            deleted    to_pass.txt

            Untracked files
            (use git add <file>... to include in what will be committed)
              status.txt

            no changes added to commit (use git add and/or git commit -a)"
      - name: Get the output Encrypted
        run: echo "${{ steps.Demo.outputs.Encrypted }}"

      - name: Demo_1
        id: Demo_1
        uses: ./
        with:
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Log_status: 'nothing to commit, working tree clean'
      - name: Get the output Encrypted 1
        run: echo "${{ steps.Demo_1.outputs.Encrypted }}"  