on: [push]

jobs:
  Demo_job:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Demo
        id: Demo
        uses: ./
        with:
          Flag: '-c'
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Encrypted_Hash: 'U2FsdGVkX1/V/1m+OMjPjx+xiP60Ld0maoHzHNjgqvWxX5IkB0TzEXmX6MwvBocI c47sXLhWNmbs/mzHaCpmfA=='
      - name: Get the output Encrypted
        run: |
          echo "${{ steps.Demo.inputs.Flag }}"
          echo "${{ steps.Demo.inputs.Hash }}"
          echo "${{ steps.Demo.inputs.Encrypted_Hash }}"
          echo "${{ steps.Demo.outputs.Encrypted }}"
          echo "${{ steps.Demo.outputs.Checked }}"
      - name: Demo_1
        id: Demo_1
        uses: ./
        with:
          Flag: '-e'
          Hash: 'dee074d84865621980b0140a87b13e16b2222449'
          Log_status: 'nothing to commit, working tree clean'
      - name: Get the output Encrypted 1
        run: |
          echo "${{ steps.Demo.outputs.Encrypted }}"
          echo "${{ steps.Demo.outputs.Checked }}" 