on: [push]

jobs:
  Demo_job:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Get the status
        uses: mathiasvr/command-output@v1
        id: Get_the_status
        with:
          run: |
            git config --global --add safe.directory '*'
            git status

      - name: Get_hash_ID
        uses: mathiasvr/command-output@v1
        id: Get_hash_ID
        with:
          run: |
            git log --format="%H" -n 1  
      
      - name: execution-checker 1
        uses: moh-alqadi-op/execution-checker@v3
        id: execution_checker_1
        with:
          Flag: '-e'
          Hash: ${{ steps.Get_hash_ID.outputs.stdout }}
          Log_status: ${{ steps.Get_the_status.outputs.stdout }}
      
      - name: Local_hash_ID
        id: Local_hash_ID
        uses: mathiasvr/command-output@v1
        with:
          run: |
            echo ${{ steps.execution_checker_1.outputs.Encrypted }}
            git notes add -f -m "${{ steps.execution_checker_1.outputs.Encrypted }}"

      - name: execution-checker-1
        uses: moh-alqadi-op/execution-checker@v3
        id: Demo
        with:
          Flag: '-c'
          Hash: ${{ steps.Get_hash_ID.outputs.stdout }}
          Encrypted_Hash: 'U2FsdGVkX18j9vw7jCERkAplP5Im9mNbxwXtBc6vAm7a8QaLFrxBaCMGfyanKnns AH1K0iJKVRoowM/jHL8IYA=='

      - name: Get the output Encrypted
        run: |
          echo "notes: $( git notes show ${{ steps.Get_hash_ID.outputs.stdout }})"
          echo "${{ steps.Demo.outputs.Checked }}"
  